### ISSUE TITLE
Change the `ABORT PROCESS` button once the job's finished 

### ISSUE THREAD

**Issue by jinzhu** [qor/worker#2]
Rightnow it is controlled in backend, which means if user started a job, and wait for the job finished without fresh current page, then the `ABORT PROCESS` will keep be there even after the job finished.

Need to move the control to frontend

![image](https://cloud.githubusercontent.com/assets/6843/13342759/fcefe756-dc7f-11e5-9b1e-f6cd2a02bdd3.png)

**Comment by jasonweng** [comment]
https://github.com/qor/worker/commit/a63fc0d3e50dd8f266e41125a0fc03935d612b03
